<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 scene.gltf --transform
Author: murilo.kleine (https://sketchfab.com/murilo.kleine)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-terra-downloadable-model-30fd7e9c4e6946ddb6fcae7a97b2b0d4
Title: Earth | Terra - Downloadable model
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/models/earth-transformed.glb', { useDraco: true });
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	const component = forwardEventHandlers();

	$: {
		$actions.ArmatureAction?.play();
	}
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Sketchfab_Scene">
			<T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
				<T.Group name="Root">
					<T.Group name="EARTH">
						<T.Mesh
							name="EARTH_0"
							geometry={gltf.nodes.EARTH_0.geometry}
							material={gltf.materials['Material.001']}
						/>
					</T.Group>
					<T.Group name="Armature">
						<T is={gltf.nodes.Armature_rootJoint} />
						<T.SkinnedMesh
							name="ATM_0"
							geometry={gltf.nodes.ATM_0.geometry}
							material={gltf.materials['Material.002']}
							skeleton={gltf.nodes.ATM_0.skeleton}
						/>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
