<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 models/raspberry_pi/scene.gltf --transform
Author: Aleksander Buzlaev (https://sketchfab.com/Aleksander2019)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/raspberry-pi-dd04d376b5c24f2a98f4c5dd3ce576a5
Title: Raspberry Pi
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/models/pi-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group rotation={[Math.PI, 0, 0]} scale={[1, 0.41, 1]}>
			<T.Mesh
				geometry={gltf.nodes.Object_4.geometry}
				material={gltf.materials.main_circuit_board}
			/>
			<T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.Metallic} />
			<T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.Plastic_black} />
			<T.Mesh
				geometry={gltf.nodes.Object_7.geometry}
				material={gltf.materials.ethernet_side_panel_decal}
			/>
			<T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_9.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_10.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_11.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_12.geometry} material={gltf.materials.metal_shiny} />
			<T.Mesh geometry={gltf.nodes.Object_13.geometry} material={gltf.materials.capacitor_shiny} />
			<T.Mesh geometry={gltf.nodes.Object_14.geometry} material={gltf.materials.capacitor_center} />
			<T.Mesh
				geometry={gltf.nodes.Object_15.geometry}
				material={gltf.materials.top_nonbroadcom_chip}
			/>
			<T.Mesh geometry={gltf.nodes.Object_16.geometry} material={gltf.materials.broadcom_chip} />
			<T.Mesh geometry={gltf.nodes.Object_17.geometry} material={gltf.materials.white_plastic} />
			<T.Mesh geometry={gltf.nodes.Object_18.geometry} material={gltf.materials.bottom_chip} />
			<T.Mesh geometry={gltf.nodes.Object_19.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_20.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_21.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_22.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_23.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_24.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_25.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_26.geometry} material={gltf.materials.gold_effect} />
			<T.Mesh geometry={gltf.nodes.Object_27.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_28.geometry} material={gltf.materials.led_yellow_off} />
			<T.Mesh geometry={gltf.nodes.Object_29.geometry} material={gltf.materials.Material} />
			<T.Mesh geometry={gltf.nodes.Object_30.geometry} material={gltf.materials.led_component} />
			<T.Mesh geometry={gltf.nodes.Object_31.geometry} material={gltf.materials.capacitor_shiny} />
			<T.Mesh
				geometry={gltf.nodes.Object_32.geometry}
				material={gltf.materials.component_FB_center}
			/>
			<T.Mesh geometry={gltf.nodes.Object_33.geometry} material={gltf.materials.resistor_shiny} />
			<T.Mesh
				geometry={gltf.nodes.Object_34.geometry}
				material={gltf.materials['resistor_center.']}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
