<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 scene.gltf --transform
Author: Bohdan Lvov (https://sketchfab.com/ostapblendercg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-whale-textured-d24d19021c724c3a9134eebcb76b0e0f
Title: Blue Whale - Textured
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/models/whale-transformed.glb', { useDraco: true });
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	const component = forwardEventHandlers();
	$: {
		$actions.Swimming?.play();
	}
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Sketchfab_Scene">
			<T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={286.42}>
				<T.Group name="WhaleAnim03fbx" rotation={[Math.PI / 2, 0, 0]}>
					<T.Group name="Object_2">
						<T.Group name="RootNode">
							<T.Group name="locator3" position={[0, 0.34, 0.67]} rotation={[0.04, 0, 0]}>
								<T.Group name="Object_7">
									<T is={gltf.nodes._rootJoint} />
									<T.SkinnedMesh
										name="Object_37"
										geometry={gltf.nodes.Object_37.geometry}
										material={gltf.materials.lambert1}
										skeleton={gltf.nodes.Object_37.skeleton}
									/>
								</T.Group>
							</T.Group>
						</T.Group>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
